# docker-compose.yml
version: '3'
services:
  app:
    build: .
    ports:
      - '3001:3001'
    environment:
      - MONGODB_URI="mongodb+srv://meetayzahamid:nEgZFxP8EZE9JzJ8@test-db.0s0q3fq.mongodb.net/?retryWrites=true&w=majority&appName=Test-db"
